version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    IMAGE_REPO_NAME: meanrev-student-demo-prod

phases:
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME

      - aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building frontend..."
      - docker build -t frontend ./frontend
      - docker tag frontend:latest $REPOSITORY_URI:frontend

      - echo "Building backend..."
      - docker build -t backend ./backend
      - docker tag backend:latest $REPOSITORY_URI:backend

  post_build:
    commands:
      - echo "Pushing frontend..."
      - docker push $REPOSITORY_URI:frontend

      - echo "Pushing backend..."
      - docker push $REPOSITORY_URI:backend
