steps:
  # Build backend
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/backend:$SHORT_SHA
      - ./backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/backend:$SHORT_SHA

  # Build frontend
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/frontend:$SHORT_SHA
      - ./frontend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/frontend:$SHORT_SHA

  # Deploy to private VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        # 1. Create directory
        gcloud compute ssh student-vm-private-1 \
          --zone=asia-south1-a \
          --tunnel-through-iap \
          --project=student-management-demoapp \
          --quiet \
          --command="mkdir -p /home/om/app"

        # 2. Upload docker-compose
        gcloud compute scp docker-compose.yml om@student-vm-private-1:/home/om/app/docker-compose.yml \
          --zone=asia-south1-a \
          --tunnel-through-iap \
          --project=student-management-demoapp \
          --quiet

        # 3. Pull and Deploy
        gcloud compute ssh student-vm-private-1 \
          --zone=asia-south1-a \
          --tunnel-through-iap \
          --project=student-management-demoapp \
          --quiet \
          --command="sudo gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet && \
                     cd /home/om/app && \
                     export TAG=$SHORT_SHA && \
                     sudo docker compose pull && \
                     sudo docker compose up -d"


images:
  - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/backend:$SHORT_SHA
  - asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/frontend:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
