steps:
  - name: 'python:3.9-slim'
    id: 'install-deps'
    entrypoint: pip
    args: ['install', 'numpy']
  # 1. Build & Push Backend (Runs in parallel)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/backend:$SHORT_SHA'
      - '--cache-from'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/backend:latest'
      - './backend'

  # 2. Build & Push Frontend (Runs in parallel)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/frontend:$SHORT_SHA'
      - '--cache-from'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/frontend:latest'
      - './frontend'

  # 3. Push images in parallel
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    waitFor: ['build-backend']
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/backend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    waitFor: ['build-frontend']
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/frontend:$SHORT_SHA']

  # 4. Deployment (Wait for both pushes to finish)
 
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    waitFor: ['push-backend', 'push-frontend']
    entrypoint: bash
    args:
      - '-c'
      - |
        # 1. Get the project number and define the OS Login user
        export PRJ_NUM=$(gcloud projects describe $PROJECT_ID --format='get(projectNumber)')
        export OS_USER="sa_$$PRJ_NUM"
        export VM_NAME="student-vm-private-1"
        export VM_ZONE="asia-south1-a"

        echo "Connecting as: $$OS_USER"

        # 2. Pre-create the directory (this also initializes the OS Login profile)
        gcloud compute ssh $$VM_NAME \
          --zone=$$VM_ZONE --tunnel-through-iap --quiet \
          --command="mkdir -p /home/$$OS_USER/app"

        # 3. Copy the docker-compose file
        gcloud compute scp docker-compose.yml $$OS_USER@$$VM_NAME:/home/$$OS_USER/app/docker-compose.yml \
          --zone=$$VM_ZONE --tunnel-through-iap --quiet

        # 4. Run the deployment commands
        gcloud compute ssh $$VM_NAME \
          --zone=$$VM_ZONE --tunnel-through-iap --quiet \
          --command="sudo gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet && \
                     cd /home/$$OS_USER/app && \
                     export TAG=$SHORT_SHA && \
                     sudo docker compose pull && \
                     sudo docker compose up -d"

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/backend:$SHORT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/studentartifact/frontend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  # This allows steps with no 'waitFor' to run immediately in parallel
  requestedVerifyOption: VERIFIED

timeout: "1200s"
