version: "3.8"

services:
  backend:
    image: asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/backend:dev
    restart: always
    ports:
      - "5000:5000"

  frontend:
    image: asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/frontend:dev
    restart: always
    ports:
      - "80:80"

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb

volumes:
  mysql-data:
