services:
  backend:
    # Use the TAG variable passed from Cloud Build
    image: asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/backend:${TAG:-latest}
    restart: always
    ports:
      - "5000:5000"

  frontend:
    # Use the TAG variable passed from Cloud Build
    image: asia-south1-docker.pkg.dev/student-management-demoapp/studentartifact/frontend:${TAG:-latest}
    restart: always
    ports:
      - "80:80"

  mysql:
    # Switched to 'minimal' to reduce download size and speed up the 'Pulling' phase
    image: mysql:8.0-minimal
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb

volumes:
  mysql-data:
